export const SagaActions = {
  //User actions
  USER_SIGN_UP:"USER_SIGN_UP_SAGA",
  USER_VERIFY_OPT: "USER_VERIFY_OPT_SAGA",
  USER_LOGIN: "USER_LOGIN_SAGA",
  USER_FORGOT_PASSWORD: 'USER_FORGOT_PASSWORD_SAGA',
  USER_UPDATE_PASSWORD: 'USER_UPDATE_PASSWORD_SAGA',
  USER_HOME_SCREEN : 'USER_HOME_SCREEN_SAGA',
  USER_GET_PROFILE: 'USER_GET_PROFILE_SAGA',
  USER_OFF_ROAD_TRIP: 'USER_OFF_ROAD_TRIP_SAGA',
  USER_ROAD_TRIP: 'USER_ROAD_TRIP_SAGA',
  USER_FILTER_API: 'USER_FILTER_API',
  USER_CREATE_TRIP: 'USER_CREATE_TRIP_saga',
  USER_GET_ALL_TRIP_LIST: 'USER_GET_ALL_TRIP_LIST_SAGA',
  USER_GET_LOCAL_TRIP_MEMORIES: 'USER_GET_LOCAL_TRIP_MEMORIES_SAGA',
  USER_REVIEW_DETAIL: 'USER_REVIEW_DETAIL_SAGA',
  USER_TRIP_MEMORIES_COUNT: 'USER_TRIP_MEMORIES_COUNT_SAGA',
  USER_GET_PROFILE_DETAIL: 'USER_GET_PROFILE_DETAIL_SAGA',
  // Guide actions

  GUIDE_GET_PROFILE: 'GUIDE_GET_PROFILE_SAGA',
  GUIDE_PAY_STATUS: 'GUIDE_PAY_STATUS_SAGA',
  GUIDE_COMPLETE_PROFILE: 'GUIDE_COMPLETE_PROFILE_SAGA'
  
};
