export default {
/* ********************* USER *************** */
TAB_NAVIGATOR: 'TAB_NAVIGATOR',
SPLASH: "SPLASH",
LANGUAGE: 'LANGUAGE',
ONBOARDING: 'ONBOARDING',
SELECT_USER: 'SELECT_USER',
WELCOME_SCREEN: 'WELCOME_SCREEN',
USER_SIGNUP_SCREEN: 'USER_SIGNUP_SCREEN',
USER_LOGIN_SCREEN: 'USER_LOGIN_SCREEN',
USER_FORGOT_PASSWORD: 'USER_FORGOT_PASSWORD',
USER_OTP_VERIFICATION: 'USER_OTP_VERIFICATION',
GUIDE_LOGIN_SCREEN: 'GUIDE_LOGIN_SCREEN',
GUIDE_SIGNUP_SCREEN: 'GUIDE_SIGNUP_SCREEN',
GUIDE_FORGOT_PASSWORD: 'GUIDE_FORGOT_PASSWORD',
GUIDE_OTP_VERIFICATION: 'GUIDE_OTP_VERIFICATION',
USER_HOME_SCREEN: 'USER_HOME_SCREEN',
MY_TRIP: 'MY_TRP',
GUIDE_EDIT_PROFILE: 'GUIDE_EDIT_PROFILE',



/* ****************** Guide ****************** */


GUIDE_HOME_SCREEN: 'GUIDE_HOME_SCREEN',
GUIDE_ACCOUNT: 'GUIDE_ACCOUNT',
USER_PROFILE: 'USER_PROFILE',
USER_FAVORITE: 'USER_FAVORITE',
USER_UPDATE_PASSWORD: 'USER_UPDATE_PASSWORD',
MY_PACKAGE: 'MY_PACKAGE',
ACCOUNT_SUCCESS: 'ACCOUNT_SUCCESS',
USER_ACCOUNT_SUCCESS: 'USER_ACCOUNT_SUCCESS',
USER_CREATE_TRIP: 'USER_CREATE_TRIP' ,
SUBSCRIPTION_PLAN: 'SUBSCRIPTION_PLAN',
CHOOSE_PAYMENT_METHOD: 'CHOOSE_PAYMENT_METHOD',
PAYMENT_DETAIL: 'PAYMENT_DETAIL',
GUIDE_COMPLETE_PROFILE:  'GUIDE_COMPLETE_PROFILE'
};
